### ISSUE TITLE
Concatenation of 2 WSI's

### ISSUE THREAD

**Issue by jesperkers** [Falcury/slideviewer#12]
Hi Pieter, a colleague asked me if it is possible to do concatenation of 2 whole slide images into 1, is that a feature easy to implement? File format is Hamamatsu in this case, example files are available. Thanks!

**Comment by Falcury** [comment]
Hi Jesper, I would not say it is easy per se, but it is definitely possible. OpenSlide could be used to read both Hamamatsu files. Then I imagine you would reposition/drag the images so that they are in the desired position for the concatenated image. Then, you would export and re-encode the whole scene as a new WSI. Would be easiest to implement if the output format were tiled TIFF instead of Hamamatsu (mostly because I already have code that can output tiled TIFF images, and OpenSlide can only read, not write). How does this sound?

**Comment by Falcury** [comment]
@jesperkers Do you know if there is still a need for this feature? It is not a high priority for me right now.

**Comment by jesperkers** [comment]
for me neither
